Ma732 driver
Ltu-Bike-trailer/control-software pull request #26
Opened 2024-11-15 16:34 UTC by Dayren43

# MA732 Driver
This pull request adds in a driver supporting the MA732 hall effect angle sensor.

```md
# I implemented the driver to enable usage of the MA732

The sensor is needed for angle measurements. The driver supports the most common commands
- read angle
- write register
- read register

As well as some niceties 
- set zero angle
- reset registers

## Testing
Not yet tested on hardware

## TODOs
Test the examples to validate it's still functional on hardware
- [ ] CAN
- [ ] MA732
```

2024-11-17 13:51 UTC, ivajon requested changes
Looks good in general, just a few nits.

2024-11-17 13:51 UTC, ivajon commented on examples/MA732.rs
> +        //blast::spawn().ok().unwrap();
Remove this

2024-11-17 13:51 UTC, ivajon commented on examples/MA732.rs
> +                driver, //cs
Remove cs comment

2024-11-17 13:51 UTC, ivajon commented on src/drivers/MA732.rs
> +pub struct Driver</* SPI: SpiBus, */ PIN: OutputPin> {
Remove /*SPI: SpiBus, */

2024-11-17 13:51 UTC, ivajon commented on src/drivers/MA732.rs
> +    // pub spi: SPI,
Remove spi field

2024-11-17 13:51 UTC, ivajon commented on src/drivers/MA732.rs
> +    /// ### note
Add new lines around the rubric

```rust
    /// returns the angle in radians.
    ///
    /// ### Note
    ///
```

2024-11-17 13:51 UTC, ivajon commented on src/drivers/MA732.rs
> +#[allow(clippy::cast_sign_loss)]
Add new line above this to be consistent.

2024-11-17 13:51 UTC, ivajon commented on src/drivers/MA732.rs
> +#[allow(clippy::cast_possible_truncation)]
ditto

2024-11-17 13:53 UTC, ivajon commented
Merge plan:

- [ ] Fix the nits
- [ ] Test driver to see that it reports correct values.
- [ ] Test the can driver again with this branch to ensure nothing broke. Or if @wiiggee1 thinks it's fine we simply ignore this test.

2024-11-19 15:57 UTC, ivajon approved these changes

2024-12-03 15:18 UTC, wiiggee1 approved these changes
Would mark this as OK for now. If you made some "unsafe proc macro changes". We might push that to another branch.

2024-12-03 15:26 UTC, merged